wip: enable full Job

diff --git a/.github/workflows/docker.yml b/.github/workflows/docker.yml
--- a/.github/workflows/docker.yml
+++ b/.github/workflows/docker.yml
@@ -167,34 +167,34 @@ jobs:
         echo "IMAGE_REF=${IMAGE_REF}" >> $GITHUB_ENV
         echo "IMAGE_REF=${IMAGE_REF}" >> $GITHUB_OUTPUT
 
-    # - name: Login to Dockerhub, public Image Registry
-    #   env:
-    #     DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
-    #   run: echo "${DOCKER_PASSWORD}" | docker login --username "${DOCKER_USER}" --password-stdin
+    - name: Login to Dockerhub, public Image Registry
+      env:
+        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
+      run: echo "${DOCKER_PASSWORD}" | docker login --username "${DOCKER_USER}" --password-stdin
 
-    # - name: Publish to DockerHub; Push Docker Image
-    #   run: |
-    #     push_success=1
-    #     docker push "${IMAGE_REF}" || push_success=0
-    #     if [ $push_success -eq 1 ]; then
-    #       echo "Docker Image "${IMAGE_REF}" pushed to DockerHub!"
-    #     else
-    #       echo "[ERROR] Docker push failed!"
-    #     fi
-    #     echo "push_success=$push_success" >> $GITHUB_ENV
+    - name: Publish to DockerHub; Push Docker Image
+      run: |
+        push_success=1
+        docker push "${IMAGE_REF}" || push_success=0
+        if [ $push_success -eq 1 ]; then
+          echo "Docker Image "${IMAGE_REF}" pushed to DockerHub!"
+        else
+          echo "[ERROR] Docker push failed!"
+        fi
+        echo "push_success=$push_success" >> $GITHUB_ENV
 
-    # - name: Logout from Dockerhub
-    #   run: docker logout
+    - name: Logout from Dockerhub
+      run: docker logout
 
-    # - name: Exit Job, with status code 0 if push was successful
-    #   run: |
-    #     if [ $push_success -eq 1 ]; then
-    #       job_status=0
-    #     else
-    #       echo "[ERROR] Docker push failed!"
-    #       job_status=1
-    #     fi
-    #     echo "Exiting with status code: $job_status"
-    #     exit $job_status
-    # outputs:
-    #   image_ref: ${{ steps.build_docker_image.outputs.IMAGE_REF }}
+    - name: Exit Job, with status code 0 if push was successful
+      run: |
+        if [ $push_success -eq 1 ]; then
+          job_status=0
+        else
+          echo "[ERROR] Docker push failed!"
+          job_status=1
+        fi
+        echo "Exiting with status code: $job_status"
+        exit $job_status
+    outputs:
+      image_ref: ${{ steps.build_docker_image.outputs.IMAGE_REF }}
