wip: sanity check that child can be triggered, debug by echoing important vars

diff --git a/.github/workflows/docker.yml b/.github/workflows/docker.yml
--- a/.github/workflows/docker.yml
+++ b/.github/workflows/docker.yml
@@ -91,12 +91,13 @@ jobs:
     # 1 0 = 2: CI/CD pure mode, aka Admit only if Pass, Require Pass, guarantee quality
     # 1 1 = 3: CI/CD with Bypass Opt, aka Admit Tested and when Test is OFF, Admit when Test OFF
 
+    if: always()
     # always() is REQUIRED to implement any run if skipped, thing!
-    if: always() && inputs.acceptance_policy != 0 && (
-        inputs.acceptance_policy == 1 || (
-        needs.*.result == 'success' && !contains(needs.*.result, 'failure') && !contains(needs.*.result, 'cancelled') || (
-        inputs.acceptance_policy == 3 && !contains(needs.*.result, 'failure') && (needs.*.result == 'skipped' || contains(needs.*.result, 'cancelled'))
-      )))
+    # if: always() && inputs.acceptance_policy != 0 && (
+    #     inputs.acceptance_policy == 1 || (
+    #     needs.*.result == 'success' && !contains(needs.*.result, 'failure') && !contains(needs.*.result, 'cancelled') || (
+    #     inputs.acceptance_policy == 3 && !contains(needs.*.result, 'failure') && (needs.*.result == 'skipped' || contains(needs.*.result, 'cancelled'))
+    #   )))
 
     # # always() is REQUIRED to implement any run if skipped, thing!
     # if: always() && inputs.acceptance_policy != '0' && (
@@ -111,66 +112,76 @@ jobs:
       DOCKER_USER: ${{ inputs.DOCKER_USER }}
     steps:
     - run: "Job Triggered with Policy: ${{ inputs.acceptance_policy }}"
-    - uses: actions/checkout@v3
-    - name: Build Docker Image from Dockerfile
-      id: build_docker_image
-      run: |
+    - run: |
+        echo === INPUTS ============
+        echo "$DOCKER_USER"
+        echo "$IMAGE_SLUG"
+        echo "$image_tag"
+        echo "$TARGET_STAGE"
+        echo ${{ inputs.target_stage }}
+        echo ${{ inputs.acceptance_policy }}
+
+
+    # - uses: actions/checkout@v3
+    # - name: Build Docker Image from Dockerfile
+    #   id: build_docker_image
+    #   run: |
         
-        # tag image with input tag if given
-        IMAGE_TAG="${{ inputs.image_tag }}"
-        # else use the git ref, which normally a branch or tag name
-        # assuming workflow is enabled for branches and v* tags
-        [ -z "$IMAGE_TAG" ] && IMAGE_TAG="${GITHUB_REF_NAME}"
+    #     # tag image with input tag if given
+    #     IMAGE_TAG="${{ inputs.image_tag }}"
+    #     # else use the git ref, which normally a branch or tag name
+    #     # assuming workflow is enabled for branches and v* tags
+    #     [ -z "$IMAGE_TAG" ] && IMAGE_TAG="${GITHUB_REF_NAME}"
 
-        IMAGE_REF="${DOCKER_USER}/${IMAGE_SLUG}:${IMAGE_TAG}"
+    #     IMAGE_REF="${DOCKER_USER}/${IMAGE_SLUG}:${IMAGE_TAG}"
 
-        echo " == Image Tag from Git Ref: $IMAGE_TAG == "
-        echo " == Image Slug: $IMAGE_SLUG == "
-        echo " == Image Ref: $IMAGE_REF == "
+    #     echo " == Image Tag from Git Ref: $IMAGE_TAG == "
+    #     echo " == Image Slug: $IMAGE_SLUG == "
+    #     echo " == Image Ref: $IMAGE_REF == "
 
-        # Set TARGET_FLAG to --target $TARGET_STAGE or an empty string
-        TARGET_FLAG="--target $TARGET_STAGE"
+    #     # Set TARGET_FLAG to --target $TARGET_STAGE or an empty string
+    #     TARGET_FLAG="--target $TARGET_STAGE"
 
-        # Remove the --target flag if DOCKER_TARGET is empty
-        [ -z "$TARGET_STAGE" ] && TARGET_FLAG=""
+    #     # Remove the --target flag if DOCKER_TARGET is empty
+    #     [ -z "$TARGET_STAGE" ] && TARGET_FLAG=""
 
-        # Build the Docker image with or without the target flag
-        docker build "$TARGET_FLAG" -t "${IMAGE_REF}" .
+    #     # Build the Docker image with or without the target flag
+    #     docker build "$TARGET_FLAG" -t "${IMAGE_REF}" .
 
-        echo " -- DOCKER BUILD DONE --"
-        echo " -- IMAGE: ${IMAGE_REF}"
+    #     echo " -- DOCKER BUILD DONE --"
+    #     echo " -- IMAGE: ${IMAGE_REF}"
 
-        echo "IMAGE_REF=${IMAGE_REF}" >> $GITHUB_ENV
-        echo "IMAGE_REF=${IMAGE_REF}" >> $GITHUB_OUTPUT
+    #     echo "IMAGE_REF=${IMAGE_REF}" >> $GITHUB_ENV
+    #     echo "IMAGE_REF=${IMAGE_REF}" >> $GITHUB_OUTPUT
 
-    - name: Login to Dockerhub, public Image Registry
-      env:
-        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
-      run: echo "${DOCKER_PASSWORD}" | docker login --username "${DOCKER_USER}" --password-stdin
+    # - name: Login to Dockerhub, public Image Registry
+    #   env:
+    #     DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
+    #   run: echo "${DOCKER_PASSWORD}" | docker login --username "${DOCKER_USER}" --password-stdin
 
-    - name: Publish to DockerHub; Push Docker Image
-      run: |
-        push_success=1
-        docker push "${IMAGE_REF}" || push_success=0
-        if [ $push_success -eq 1 ]; then
-          echo "Docker Image "${IMAGE_REF}" pushed to DockerHub!"
-        else
-          echo "[ERROR] Docker push failed!"
-        fi
-        echo "push_success=$push_success" >> $GITHUB_ENV
+    # - name: Publish to DockerHub; Push Docker Image
+    #   run: |
+    #     push_success=1
+    #     docker push "${IMAGE_REF}" || push_success=0
+    #     if [ $push_success -eq 1 ]; then
+    #       echo "Docker Image "${IMAGE_REF}" pushed to DockerHub!"
+    #     else
+    #       echo "[ERROR] Docker push failed!"
+    #     fi
+    #     echo "push_success=$push_success" >> $GITHUB_ENV
 
-    - name: Logout from Dockerhub
-      run: docker logout
+    # - name: Logout from Dockerhub
+    #   run: docker logout
 
-    - name: Exit Job, with status code 0 if push was successful
-      run: |
-        if [ $push_success -eq 1 ]; then
-          job_status=0
-        else
-          echo "[ERROR] Docker push failed!"
-          job_status=1
-        fi
-        echo "Exiting with status code: $job_status"
-        exit $job_status
-    outputs:
-      image_ref: ${{ steps.build_docker_image.outputs.IMAGE_REF }}
+    # - name: Exit Job, with status code 0 if push was successful
+    #   run: |
+    #     if [ $push_success -eq 1 ]; then
+    #       job_status=0
+    #     else
+    #       echo "[ERROR] Docker push failed!"
+    #       job_status=1
+    #     fi
+    #     echo "Exiting with status code: $job_status"
+    #     exit $job_status
+    # outputs:
+    #   image_ref: ${{ steps.build_docker_image.outputs.IMAGE_REF }}
